apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  securityContext:
    runAsUser: 5000
    runAsGroup: 5000
  containers:
  - image: mauritori/busybox
    name: busybox
    command: ["sleep", "infinity"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
